name: SerenadaiOS
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.10
    PRODUCT_BUNDLE_IDENTIFIER: app.serenada.ios
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    TARGETED_DEVICE_FAMILY: "1,2"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    ENABLE_USER_SCRIPT_SANDBOXING: NO
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.11.0
targets:
  SerenadaiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Resources
        excludes:
          - Info.plist
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: Serenada
        UILaunchScreen: {}

        NSCameraUsageDescription: Serenada needs camera access for video calls.
        NSMicrophoneUsageDescription: Serenada needs microphone access for audio calls.
        NSLocalNetworkUsageDescription: Serenada may access local network interfaces for call connectivity checks.
        UIApplicationSupportsIndirectInputEvents: YES
        UIBackgroundModes:
          - audio
          - voip
        LSApplicationQueriesSchemes:
          - https
    preBuildScripts:
      - name: Verify WebRTC Checksum
        path: scripts/verify_webrtc_checksum.sh
        basedOnDependencyAnalysis: false
    dependencies:
      - framework: Vendor/WebRTC/WebRTC.xcframework
        embed: true
        codeSign: true
      - package: Firebase
        product: FirebaseMessaging
      - target: SerenadaNotificationService
        embed: true
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/SerenadaiOS.entitlements
  SerenadaNotificationService:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NotificationService
      - path: Sources/Core/Push/PushKeyStore.swift
    info:
      path: NotificationService/Info.plist
      properties:
        CFBundleDisplayName: Serenada Notification Service
        NSExtension:
          NSExtensionPointIdentifier: com.apple.usernotifications.service
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).NotificationService"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.serenada.ios.notificationservice
        INFOPLIST_FILE: NotificationService/Info.plist
        CODE_SIGN_ENTITLEMENTS: NotificationService/NotificationService.entitlements
  SerenadaiOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests
    dependencies:
      - target: SerenadaiOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: app.serenada.ios.tests
  SerenadaiOSUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: UITests
    dependencies:
      - target: SerenadaiOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: app.serenada.ios.uitests
schemes:
  SerenadaiOS:
    build:
      targets:
        SerenadaiOS: all
    test:
      targets:
        - SerenadaiOSTests
        - SerenadaiOSUITests
